language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - php src/code-checker.php --short-arrays
