language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.1

install:
  - composer require --dev --no-update phpstan/phpstan-shim:^0.7
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-stable
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint
  - travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar

script:
  - php vendor/bin/phpunit --coverage-clover tests/coverage.xml -c tests/phpunit.xml
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - php vendor/bin/phpcs --standard=ruleset.xml --encoding=utf-8 -sp KdybyCodingStandard/ tests/
  - php vendor/phpstan/phpstan-shim/phpstan.phar analyse --ansi --no-progress -l7 -c phpstan.neon KdybyCodingStandard/ tests/

after_script:
  - php /tmp/coveralls.phar --verbose --config tests/.coveralls.yml || true

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
